import {
  type Program,
  type EmitContext,
  emitFile,
  resolvePath,
} from "@typespec/compiler";
import {
  collectServices,
  clientFileName,
  serverFileName,
  toPascalCase,
  type ServiceInfo,
  type RpcInfo,
  type StreamType,
} from "@speconn-rpc/typespec-emitter-speconn-core";
import { getNamespaceFullName } from "@typespec/compiler";

function goPackageName(service: ServiceInfo): string {
  const nsName = getNamespaceFullName(service.namespace);
  return nsName.split(".").map(s => s.replace(/([a-z])([A-Z])/g, "$1_$2").replace(/([A-Z])([A-Z][a-z])/g, "$1_$2").toLowerCase()).join("_");
}

function goTypeName(model: { name?: string } | null): string {
  if (!model || !model.name) return "any";
  return toPascalCase(model.name);
}

function methodPascal(rpc: RpcInfo): string {
  return toPascalCase(rpc.name);
}

function transportVarName(service: ServiceInfo): string {
  const name = service.serviceName;
  return `_${name.charAt(0).toLowerCase() + name.slice(1)}Transport`;
}

function setTransportFuncName(service: ServiceInfo): string {
  return `Set${service.serviceName}Transport`;
}

function getTransportFuncName(service: ServiceInfo): string {
  const name = service.serviceName;
  return `get${name.charAt(0).toLowerCase() + name.slice(1)}Transport`;
}

function clientMethodBody(rpc: RpcInfo, service: ServiceInfo): string {
  const reqType = goTypeName(rpc.inputType);
  const resType = goTypeName(rpc.outputType);
  const transportGetter = getTransportFuncName(service);

  const callerDecl = `\tcaller := speconnrpc.NewSpeconnCaller[${reqType}, ${resType}](
\t\t"${rpc.path}",
\t\t${transportGetter}(),
\t\t${reqType}Codec,
\t\t${resType}Codec,
\t)`;

  const optsBlock = `\tvar opts speconnrpc.CallOptions
\tif len(options) > 0 { opts = options[0] }`;

  switch (rpc.streamType) {
    case "unary":
      return `${callerDecl}
${optsBlock}
\treturn caller.Call(req, opts)`;
    case "server":
      return `${callerDecl}
${optsBlock}
\treturn caller.ServerStream(req, opts)`;
    case "client":
      return `${callerDecl}
${optsBlock}
\treturn caller.ClientStream(opts, reqs)`;
    case "bidi":
      return `${callerDecl}
${optsBlock}
\treturn caller.Bidi(opts, reqs)`;
  }
}

function generateClientFile(service: ServiceInfo): string {
  const pkgName = goPackageName(service);
  const transportVar = transportVarName(service);
  const setFunc = setTransportFuncName(service);
  const getFunc = getTransportFuncName(service);
  const lines: string[] = [];

  lines.push("// Generated by typespec-emitter-speconn-golang. DO NOT EDIT.");
  lines.push(`package ${pkgName}`);
  lines.push("");
  lines.push("import (");
  lines.push('\tspeconnrpc "speconn-rpc.dev/speconn-rpc-golang"');
  lines.push(")");
  lines.push("");

  lines.push(`var ${transportVar} speconnrpc.SpeconnTransport`);
  lines.push("");
  lines.push(`func ${setFunc}(t speconnrpc.SpeconnTransport) {`);
  lines.push(`\t${transportVar} = t`);
  lines.push("}");
  lines.push("");
  lines.push(`func ${getFunc}() speconnrpc.SpeconnTransport {`);
  lines.push(`\tif ${transportVar} != nil {`);
  lines.push(`\t\treturn ${transportVar}`);
  lines.push("\t}");
  lines.push("\treturn speconnrpc.GetDefaultTransport()");
  lines.push("}");
  lines.push("");

  for (const rpc of service.rpcs) {
    const reqType = goTypeName(rpc.inputType);
    const resType = goTypeName(rpc.outputType);
    const methodName = methodPascal(rpc);

    if (rpc.streamType === "unary") {
      lines.push(`func ${methodName}(req ${reqType}, options ...speconnrpc.CallOptions) (${resType}, error) {`);
    } else if (rpc.streamType === "server") {
      lines.push(`func ${methodName}(req ${reqType}, options ...speconnrpc.CallOptions) <-chan speconnrpc.StreamResult[${resType}] {`);
    } else if (rpc.streamType === "client") {
      lines.push(`func ${methodName}(reqs <-chan ${reqType}, options ...speconnrpc.CallOptions) (${resType}, error) {`);
    } else {
      lines.push(`func ${methodName}(reqs <-chan ${reqType}, options ...speconnrpc.CallOptions) <-chan speconnrpc.StreamResult[${resType}] {`);
    }

    lines.push(clientMethodBody(rpc, service));
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function serverInterfaceMethod(rpc: RpcInfo): string {
  const reqType = goTypeName(rpc.inputType);
  const resType = goTypeName(rpc.outputType);
  const methodName = methodPascal(rpc);

  switch (rpc.streamType) {
    case "unary":
      return `\t${methodName}(ctx *speconnrpc.SpeconnContext, req ${reqType}) (${resType}, error)`;
    case "server":
      return `\t${methodName}(ctx *speconnrpc.SpeconnContext, req ${reqType}) <-chan ${resType}`;
    case "client":
      return `\t${methodName}(ctx *speconnrpc.SpeconnContext, reqs <-chan ${reqType}) (${resType}, error)`;
    case "bidi":
      return `\t${methodName}(ctx *speconnrpc.SpeconnContext, reqs <-chan ${reqType}) <-chan ${resType}`;
  }
}

function registerFunctionName(rpc: RpcInfo): string {
  switch (rpc.streamType) {
    case "unary":
      return "RegisterUnary";
    case "server":
      return "RegisterServerStream";
    case "client":
      return "RegisterClientStream";
    case "bidi":
      return "RegisterBidi";
  }
}

function registerHandlerLambda(rpc: RpcInfo): string {
  const reqType = goTypeName(rpc.inputType);
  const resType = goTypeName(rpc.outputType);
  const methodName = methodPascal(rpc);

  switch (rpc.streamType) {
    case "unary":
      return `func(ctx *speconnrpc.SpeconnContext, req ${reqType}) (${resType}, error) {\n\t\t\treturn impl.${methodName}(ctx, req)\n\t\t}`;
    case "server":
      return `func(ctx *speconnrpc.SpeconnContext, req ${reqType}) <-chan ${resType} {\n\t\t\treturn impl.${methodName}(ctx, req)\n\t\t}`;
    case "client":
      return `func(ctx *speconnrpc.SpeconnContext, reqs <-chan ${reqType}) (${resType}, error) {\n\t\t\treturn impl.${methodName}(ctx, reqs)\n\t\t}`;
    case "bidi":
      return `func(ctx *speconnrpc.SpeconnContext, reqs <-chan ${reqType}) <-chan ${resType} {\n\t\t\treturn impl.${methodName}(ctx, reqs)\n\t\t}`;
  }
}

function generateServerFile(service: ServiceInfo): string {
  const pkgName = goPackageName(service);
  const serviceName = service.serviceName;
  const lines: string[] = [];

  lines.push("// Generated by typespec-emitter-speconn-golang. DO NOT EDIT.");
  lines.push(`package ${pkgName}`);
  lines.push("");
  lines.push("import (");
  lines.push('\tspeconnrpc "speconn-rpc.dev/speconn-rpc-golang"');
  lines.push(")");
  lines.push("");

  lines.push(`type ${serviceName}Service interface {`);
  for (const rpc of service.rpcs) {
    lines.push(serverInterfaceMethod(rpc));
  }
  lines.push("}");
  lines.push("");

  lines.push(`func Register${serviceName}(router *speconnrpc.SpeconnRouter, impl ${serviceName}Service) {`);
  for (const rpc of service.rpcs) {
    const reqType = goTypeName(rpc.inputType);
    const resType = goTypeName(rpc.outputType);
    const regFn = registerFunctionName(rpc);
    const lambda = registerHandlerLambda(rpc);

    lines.push(`\tspeconnrpc.${regFn}[${reqType}, ${resType}](router, "${rpc.path}", ${reqType}Codec, ${resType}Codec, ${lambda})`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  const services = collectServices(program);
  const outputDir = context.emitterOutputDir;
  const opts = (context as any).options ?? {};
  const emitClient = !opts["server-only"];
  const emitServer = !opts["client-only"];

  for (const service of services) {
    if (emitClient) {
      const clientContent = generateClientFile(service);
      const clientName = clientFileName(service) + ".go";
      await emitFile(program, { path: resolvePath(outputDir, clientName), content: clientContent });
    }
    if (emitServer) {
      const serverContent = generateServerFile(service);
      const serverName = serverFileName(service) + ".go";
      await emitFile(program, { path: resolvePath(outputDir, serverName), content: serverContent });
    }
  }
}
