import {
  type Program,
  type EmitContext,
  emitFile,
  resolvePath,
} from "@typespec/compiler";
import {
  collectServices,
  clientFileName,
  serverFileName,
  toPascalCase,
  type ServiceInfo,
  type RpcInfo,
  type StreamType,
} from "@speconn-rpc/typespec-emitter-speconn-core";
import { getNamespaceFullName } from "@typespec/compiler";

function goPackageName(service: ServiceInfo): string {
  const nsName = getNamespaceFullName(service.namespace);
  const parts = nsName.split(".");
  return parts[parts.length - 1].toLowerCase();
}

function goTypeName(model: { name?: string } | null): string {
  if (!model || !model.name) return "any";
  return toPascalCase(model.name);
}

function methodPascal(rpc: RpcInfo): string {
  return toPascalCase(rpc.name);
}

function callerVarName(rpc: RpcInfo): string {
  return `_caller${methodPascal(rpc)}`;
}

function callerInitBlock(rpc: RpcInfo): string {
  const varName = callerVarName(rpc);
  const reqType = goTypeName(rpc.inputType);
  const resType = goTypeName(rpc.outputType);
  return `\t${varName} = speconnrpc.NewSpeconnCaller[${reqType}, ${resType}](
\t\t"${rpc.path}",
\t\tspeconnrpc.GetDefaultTransport(),
\t\ttypes.${reqType}Codec,
\t\ttypes.${resType}Codec,
\t)`;
}

function clientCallBody(rpc: RpcInfo): string {
  const varName = callerVarName(rpc);
  switch (rpc.streamType) {
    case "unary":
      return `\tif ${varName} == nil {
${callerInitBlock(rpc)}
\t}
\tvar opts speconnrpc.CallOptions
\tif len(options) > 0 { opts = options[0] }
\treturn ${varName}.Call(req, opts)`;
    case "server":
      return `\tif ${varName} == nil {
${callerInitBlock(rpc)}
\t}
\tvar opts speconnrpc.CallOptions
\tif len(options) > 0 { opts = options[0] }
\treturn ${varName}.ServerStream(req, opts)`;
    case "client":
      return `\tif ${varName} == nil {
${callerInitBlock(rpc)}
\t}
\tvar opts speconnrpc.CallOptions
\tif len(options) > 0 { opts = options[0] }
\treturn ${varName}.ClientStream(opts, reqs)`;
    case "bidi":
      return `\tif ${varName} == nil {
${callerInitBlock(rpc)}
\t}
\tvar opts speconnrpc.CallOptions
\tif len(options) > 0 { opts = options[0] }
\treturn ${varName}.Bidi(opts, reqs)`;
  }
}

function generateClientFile(service: ServiceInfo): string {
  const pkgName = goPackageName(service);
  const lines: string[] = [];

  lines.push("// Generated by typespec-emitter-speconn-golang. DO NOT EDIT.");
  lines.push(`package ${pkgName}`);
  lines.push("");
  lines.push("import (");
  lines.push('\tspeconnrpc "speconn-rpc.dev/speconn-rpc-golang"');
  lines.push(")");
  lines.push("");

  for (const rpc of service.rpcs) {
    const reqType = goTypeName(rpc.inputType);
    const resType = goTypeName(rpc.outputType);
    const varName = callerVarName(rpc);
    const methodName = methodPascal(rpc);

    lines.push(`var ${varName} *speconnrpc.SpeconnCaller[${reqType}, ${resType}]`);
    lines.push("");

    if (rpc.streamType === "unary") {
      lines.push(`func ${methodName}(req ${reqType}, options ...speconnrpc.CallOptions) (${resType}, error) {`);
    } else if (rpc.streamType === "server") {
      lines.push(`func ${methodName}(req ${reqType}, options ...speconnrpc.CallOptions) <-chan speconnrpc.StreamResult[${resType}] {`);
    } else if (rpc.streamType === "client") {
      lines.push(`func ${methodName}(reqs <-chan ${reqType}, options ...speconnrpc.CallOptions) (${resType}, error) {`);
    } else {
      lines.push(`func ${methodName}(reqs <-chan ${reqType}, options ...speconnrpc.CallOptions) <-chan speconnrpc.StreamResult[${resType}] {`);
    }

    lines.push(clientCallBody(rpc));
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function serverInterfaceMethod(rpc: RpcInfo): string {
  const reqType = goTypeName(rpc.inputType);
  const resType = goTypeName(rpc.outputType);
  const methodName = methodPascal(rpc);

  switch (rpc.streamType) {
    case "unary":
      return `\t${methodName}(ctx *speconnrpc.SpeconnContext, req ${reqType}) (${resType}, error)`;
    case "server":
      return `\t${methodName}(ctx *speconnrpc.SpeconnContext, req ${reqType}) <-chan ${resType}`;
    case "client":
      return `\t${methodName}(ctx *speconnrpc.SpeconnContext, reqs <-chan ${reqType}) (${resType}, error)`;
    case "bidi":
      return `\t${methodName}(ctx *speconnrpc.SpeconnContext, reqs <-chan ${reqType}) <-chan ${resType}`;
  }
}

function registerFunctionName(rpc: RpcInfo): string {
  switch (rpc.streamType) {
    case "unary":
      return "RegisterUnary";
    case "server":
      return "RegisterServerStream";
    case "client":
      return "RegisterClientStream";
    case "bidi":
      return "RegisterBidi";
  }
}

function registerHandlerLambda(rpc: RpcInfo): string {
  const reqType = goTypeName(rpc.inputType);
  const resType = goTypeName(rpc.outputType);
  const methodName = methodPascal(rpc);

  switch (rpc.streamType) {
    case "unary":
      return `func(ctx *speconnrpc.SpeconnContext, req ${reqType}) (${resType}, error) {\n\t\t\treturn impl.${methodName}(ctx, req)\n\t\t}`;
    case "server":
      return `func(ctx *speconnrpc.SpeconnContext, req ${reqType}) <-chan ${resType} {\n\t\t\treturn impl.${methodName}(ctx, req)\n\t\t}`;
    case "client":
      return `func(ctx *speconnrpc.SpeconnContext, reqs <-chan ${reqType}) (${resType}, error) {\n\t\t\treturn impl.${methodName}(ctx, reqs)\n\t\t}`;
    case "bidi":
      return `func(ctx *speconnrpc.SpeconnContext, reqs <-chan ${reqType}) <-chan ${resType} {\n\t\t\treturn impl.${methodName}(ctx, reqs)\n\t\t}`;
  }
}

function generateServerFile(service: ServiceInfo): string {
  const pkgName = goPackageName(service);
  const serviceName = service.serviceName;
  const lines: string[] = [];

  lines.push("// Generated by typespec-emitter-speconn-golang. DO NOT EDIT.");
  lines.push(`package ${pkgName}`);
  lines.push("");
  lines.push("import (");
  lines.push('\tspeconnrpc "speconn-rpc.dev/speconn-rpc-golang"');
  lines.push(")");
  lines.push("");

  lines.push(`type ${serviceName}Service interface {`);
  for (const rpc of service.rpcs) {
    lines.push(serverInterfaceMethod(rpc));
  }
  lines.push("}");
  lines.push("");

  lines.push(`func Register${serviceName}(router *speconnrpc.SpeconnRouter, impl ${serviceName}Service) {`);
  for (const rpc of service.rpcs) {
    const reqType = goTypeName(rpc.inputType);
    const resType = goTypeName(rpc.outputType);
    const regFn = registerFunctionName(rpc);
    const lambda = registerHandlerLambda(rpc);

    lines.push(`\tspeconnrpc.${regFn}[${reqType}, ${resType}](router, "${rpc.path}", types.${reqType}Codec, types.${resType}Codec, ${lambda})`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export async function $onEmit(context: EmitContext): Promise<void> {
  const program = context.program;
  const services = collectServices(program);
  const outputDir = context.emitterOutputDir;

  for (const service of services) {
    const clientContent = generateClientFile(service);
    const serverContent = generateServerFile(service);

    const clientName = clientFileName(service) + ".go";
    const serverName = serverFileName(service) + ".go";

    await emitFile(program, {
      path: resolvePath(outputDir, clientName),
      content: clientContent,
    });
    await emitFile(program, {
      path: resolvePath(outputDir, serverName),
      content: serverContent,
    });
  }
}
